config/routes.rb
Testingapp::Application.routes.draw do
	resources :items

	root 'items#index'	

  	devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  	get 'users/:id' => 'users#show' , as: :user

  	resources :users
end  

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
	# attr_accessible :picture, :name, :description, :buy_price, :store, :image, :size_id


	has_attached_file :picture, styles: { medium: "300x300>" }

	validates_attachment :picture, presence: true,
									content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
									size: { less_than: 2.megabytes }

	belongs_to :user

	def picture_url 
		return picture.url 
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :omniauthable, 
         :recoverable, :rememberable, :trackable, :validatable

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.nickname
	    user.image = auth.info.image
	  end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	  	new session["devise.user_attributes"] do |user|
	    
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
		super && provider.blank?		
	end

	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_filter :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to users_path, :alert => exception.message
  end


  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json

  def index
    @items = Item.all

    respond_to do |format|
      format.html { render html: items_path }
      format.json { render json: @items.as_json(methods: :picture_url) }
      # format.json { render json: @items.picture_url }
    end    
  end



  # GET /items/1
  # GET /items/1.json
  def show
    
  end

  # GET /items/new
  def new
    # @item = Item.new
    @item = current_user.items.new

  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    # @item = Item.new(item_params)
    @item = current_user.items.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :buy_price, :size_id, :image, :store, :picture)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def all
		user = User.from_omniauth(request.env["omniauth.auth"])

		if user.persisted?
			flash[:notice] = "Signed in with Twitter."
			
      		sign_in_and_redirect user
		else
      		session["devise.user_attributes"] = user.attributes
      		redirect_to new_user_registration_url			
		end

	end

	alias_method :twitter, :all
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])    
    @items = @user.items

    respond_to do |format|
      format.html { render html: users_path }
      format.json { render json: @items }
    end   
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/home/index.html.erb
<!-- <div class="container"> -->
	<h3>THRIFT FEED</h3>
	<% @users.each do |user| %>
	  <p>User: <%=link_to user.name, user %></p>
	<% end %>	
<!-- </div>		 -->

app/views/items/_form.html.erb
<%= simple_form_for @item, html: {multipart: true} do |f| %>

  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :buy_price %>
    <%= f.input :store %>
    <%= f.input :image %>
    <%= f.input :size_id %>

    <%= f.input :picture%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<!-- <div class="container"> -->
<%= link_to 'New Item', new_item_path, class: "btn btn-large btn-warning" %>
<!-- </div>   -->
<!-- <div class="container index_wrapper"> -->
  
  <!-- <div class="row box_row"> -->
  <% @items.each do |item| %>
    
      <div class="box span3">        
          <!-- <img src="<%= item.image %>" alt=""> -->
          <%= image_tag item.picture(:medium) %>
          <%= item.picture.url %>

          <div class="content">
            <h5><%= item.name %></h5>            
            <p><%= item.store %></p>
            <p><b>Buy Now: </b>$<%= item.buy_price %></p>
            <p><b>Size: </b><%= item.size_id %></p>
            <p><b>Store: </b> <%= item.store %></p>   
            <p><b>Description:</b> <br> <%= item.description %></p>

            <p><b>User: <%= link_to item.user.name, user_path(item.user.id) %></b></p>
            
            <%= link_to 'Show', item, class: "btn btn-mini btn-warning" %>
            <%#= link_to 'Edit', edit_item_path(item), class: "btn btn-mini btn-warning" %>
            <%#= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-mini btn-warning"%>            
          </div>
      </div>
    
  <% end %>
  <!-- </div> -->
<!-- </div> -->

app/views/items/new.html.erb
<h1>New Thrift Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="span4">
	<p>
	  <strong>Name:</strong>
	  <%= @item.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @item.description %>
	</p>

	<p>
	  <strong>Buy price:</strong>
	  <%= @item.buy_price %>
	</p>

	<p>
	  <strong>Size:</strong>
	  <%= @item.size_id %>
	</p>
	<%= image_tag @item.picture %>
</div>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <a href="#"><img src="assets/logo.png" class="brand"></a> -->

<a href="/items" class="brand head_logo">
  <img src="<%= asset_path("logo.png") %>" alt="">
</a>

<ul class="nav nav_options">


  <% if user_signed_in? %>


  <% else %>

    <li>
      <%= link_to 'Login', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Twitter', user_omniauth_authorize_path(:twitter) %>
    </link_to>

  <% end %>


  <% if user_signed_in? %>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle custom_drop" data-toggle="dropdown">
          <%= current_user.name %>
          <img src="<%= current_user.image %>" class="dp_image">
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to 'My Items', user_path(current_user) %>
        </li>
        <li>
          <%= link_to 'Edit account', edit_user_registration_path %>
        </li>
        <li>      
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>        
      </ul>
    </li>

    <% if current_user.has_role? :admin %>

      <li>
        <%= link_to 'Admin', users_path %>
      </li>

    <% end %>

  <% else %>
    <li>
      <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Thriftly" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Thriftly" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  
  <body class="<%= controller_name %> <%= action_name %>">

    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner nav_custom">
        <div class="container ">
          <%=  render 'layouts/navigation' %>
        </div>
      </nav>
    </div>

    <div id="main" role="main">
      <div class="container large_wrapper">
        <!-- <div class="content"> -->
           <div class="row">
            <!-- <div class="span12"> -->
              <%= render 'layouts/messages' %>
              
              <%= yield %>
            <!-- </div> -->
          </div>
          <footer>
          </footer>
        <!-- </div> -->
      </div> 
      <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>

<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

<%= @items.name %>

  <% @items.each do |item| %>
    
      <div class="box span3">        
          <!-- <img src="<%= item.image %>" alt=""> -->
          <%= image_tag item.picture(:medium) %>
          <%= item.picture.url %>

          <div class="content">
            <h5><%= item.name %></h5>
            
            <p><%= item.store %></p>
            <p><b>Buy Now: </b>$<%= item.buy_price %></p>
            <p><b>Size: </b><%= item.size_id %></p>
            <p><b>Store: </b> <%= item.store %></p>  
            <p><b>Description:</b> <br> <%= item.description %></p>
            <%= link_to 'Show', item, class: "btn btn-mini btn-warning" %>
            <%= link_to 'Edit', edit_item_path(item), class: "btn btn-mini btn-warning" %>
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-mini btn-warning"%>            
          </div>
      </div>
    
  <% end %>